import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { getExpectedTwilioSignature } from "twilio";
import { validateTwilioSignature, shouldSkipTwilioValidation } from "@/lib/twilio-auth";

// A deterministic auth token and webhook URL for testing.
// getExpectedTwilioSignature computes the same HMAC-SHA1 Twilio itself uses,
// so these tests exercise the real signature algorithm.
const AUTH_TOKEN = "test_auth_token_32_characters_abcd";
const WEBHOOK_URL = "https://founditcampus.com/api/twilio/inbound";
const PARAMS: Record<string, string> = {
  Body: "I lost my red laptop near the library",
  From: "+14155551234",
  To: "+18005550100",
  MessageSid: "SM1234567890abcdef1234567890abcdef",
};

function makeRequest(url: string, sigHeader: string | null): Request {
  const headers = new Headers();
  if (sigHeader !== null) headers.set("X-Twilio-Signature", sigHeader);
  return new Request(url, { method: "POST", headers });
}

describe("validateTwilioSignature", () => {
  const savedToken = process.env.TWILIO_AUTH_TOKEN;

  beforeEach(() => {
    process.env.TWILIO_AUTH_TOKEN = AUTH_TOKEN;
  });

  afterEach(() => {
    if (savedToken === undefined) {
      delete process.env.TWILIO_AUTH_TOKEN;
    } else {
      process.env.TWILIO_AUTH_TOKEN = savedToken;
    }
  });

  it("returns true for a valid Twilio-signed request (real HMAC)", () => {
    // Signature generated by the same algorithm Twilio uses.
    const sig = getExpectedTwilioSignature(AUTH_TOKEN, WEBHOOK_URL, PARAMS);
    const req = makeRequest(WEBHOOK_URL, sig);
    expect(validateTwilioSignature(req, PARAMS)).toBe(true);
  });

  it("returns false when X-Twilio-Signature header is missing", () => {
    const req = makeRequest(WEBHOOK_URL, null);
    expect(validateTwilioSignature(req, PARAMS)).toBe(false);
  });

  it("returns false when X-Twilio-Signature is wrong", () => {
    const req = makeRequest(WEBHOOK_URL, "AAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
    expect(validateTwilioSignature(req, PARAMS)).toBe(false);
  });

  it("returns false for empty params (empty body)", () => {
    // Even a correctly-computed signature for empty params is rejected — Twilio
    // always sends at least From + Body; empty params means the body was forged
    // or stripped.
    const sigForEmpty = getExpectedTwilioSignature(AUTH_TOKEN, WEBHOOK_URL, {});
    const req = makeRequest(WEBHOOK_URL, sigForEmpty);
    expect(validateTwilioSignature(req, {})).toBe(false);
  });

  it("returns false when TWILIO_AUTH_TOKEN env var is not set", () => {
    delete process.env.TWILIO_AUTH_TOKEN;
    const sig = getExpectedTwilioSignature(AUTH_TOKEN, WEBHOOK_URL, PARAMS);
    const req = makeRequest(WEBHOOK_URL, sig);
    expect(validateTwilioSignature(req, PARAMS)).toBe(false);
  });

  it("returns false when URL does not match the signed URL", () => {
    // Signature was computed for WEBHOOK_URL but request arrives at a different URL.
    const sig = getExpectedTwilioSignature(AUTH_TOKEN, WEBHOOK_URL, PARAMS);
    const req = makeRequest("https://evil.example.com/api/twilio/inbound", sig);
    expect(validateTwilioSignature(req, PARAMS)).toBe(false);
  });
});

describe("shouldSkipTwilioValidation", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("returns false in production even when TWILIO_SKIP_VALIDATION=true", () => {
    vi.stubEnv("NODE_ENV", "production");
    vi.stubEnv("TWILIO_SKIP_VALIDATION", "true");
    expect(shouldSkipTwilioValidation()).toBe(false);
  });

  it("returns false in development when TWILIO_SKIP_VALIDATION is not set", () => {
    vi.stubEnv("NODE_ENV", "development");
    vi.stubEnv("TWILIO_SKIP_VALIDATION", "");
    expect(shouldSkipTwilioValidation()).toBe(false);
  });

  it("returns true only when NODE_ENV=development AND TWILIO_SKIP_VALIDATION=true", () => {
    vi.stubEnv("NODE_ENV", "development");
    vi.stubEnv("TWILIO_SKIP_VALIDATION", "true");
    expect(shouldSkipTwilioValidation()).toBe(true);
  });
});
